# Generated by Django 2.1.3 on 2019-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllLanguages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('languageName', models.CharField(max_length=200, null=True)),
                ('className', models.CharField(max_length=200, null=True)),
                ('methodName', models.CharField(max_length=200, null=True)),
                ('parameterName', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
