# Generated by Django 2.0.13 on 2019-08-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alllanguages',
            name='id',
        ),
        migrations.AddField(
            model_name='alllanguages',
            name='languageName',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
