# Generated by Django 2.0.13 on 2019-09-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllanguages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
