# Generated by Django 2.0.13 on 2019-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_parser', '0002_auto_20190811_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllanguages',
            name='link',
            field=models.URLField(default=0),
        ),
    ]
