# Generated by Django 2.1.3 on 2019-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('seq', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('keywords', models.CharField(blank=True, max_length=128, null=True)),
                ('entities', models.CharField(blank=True, max_length=128, null=True)),
                ('categories', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('check', models.TextField(blank=True, null=True)),
                ('etc', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
