# Generated by Django 2.1 on 2018-09-29 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('seq', models.IntegerField(primary_key=True, serialize=False)),
                ('keywords', models.CharField(max_length=128)),
                ('entities', models.CharField(max_length=128)),
                ('categories', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('etc', models.CharField(max_length=128)),
            ],
        ),
    ]
