# Generated by Django 2.1.3 on 2019-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
