# Generated by Django 2.1.3 on 2019-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20191121_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='categories',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
