# Generated by Django 2.1 on 2018-11-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20181002_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='check',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='categories',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='entities',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='etc',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='keywords',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
