# Generated by Django 2.1 on 2018-11-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_comparesource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompareSource',
        ),
    ]
